import Head from 'next/head'


export default function Home() {
  return (
    <div className='min-h-screen w-full bg-main'>
      <Head>
        <title>pepper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,700;1,100;1,900&display=swap" rel="stylesheet" />

      </Head>
      <div className="w-full h-24 bg-main2 ">
        <div className="w-full h-full flex items-center p-3 px-6">
          <h1 className='font-robo text-4xl font-extrabold'>pepper</h1>
        </div>
      </div>
   
    </div>
  )
}
